# Generated by Django 5.0.6 on 2024-05-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('color', models.CharField(default='', help_text='应援色', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('producer', models.CharField(help_text='生产商', max_length=30)),
                ('type', models.CharField(help_text='谷子类型', max_length=20)),
                ('productDate', models.TextField()),
                ('series', models.CharField(help_text='来自系列', max_length=50)),
                ('size', models.CharField(help_text='谷子尺寸', max_length=50)),
                ('character', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vueapi.character')),
                ('goodsIp', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vueapi.goodsip')),
            ],
        ),
    ]
